version: '3.8'

services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    container_name: angular-docker-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
